### ISSUE TITLE
How to install spconv with docker

### ISSUE THREAD

**Issue by jamesheatonrdm** [Eaphan/GLENet#11]
Firstsly, the link to spconv is wrong as it takes you to version 2 which is not compatible with this project.

You say you need to use their dockerfile when using PyTorch > 1.4, which I am.

Going to the correct version of spconv, found here - https://github.com/traveller59/spconv/tree/v1.2.1 - all it says re Docker is to run the command docker pull scrin/dev-spconv. 

What do I do after this? There is no documentation for this at all. Any help would be appreciated.

**Comment by Eaphan** [comment]
Hi. I do not test the project with spconv 2.0. I guess it is also ok if you make hot fix on the codebase.

Actually, installing the spconv1.2 is not easy sometimes. You can show your log here or spconv repo, and I can help you analyze it.

**Comment by jamesheatonrdm** [comment]
Hi @Eaphan I gave up with docker and looked at some other issues here and it looks like you can use spconv 2. I just installed the most recent version via pip and it seems to be working OK at the moment.

Thanks for the quick reply anyway

**Comment by Eaphan** [comment]
Star the repo if you like it. Thanks.:)
