### ISSUE TITLE
AttributeError: module 'spconv' has no attribute 'SparseModule'

### ISSUE THREAD

**Issue by 15041909992** [Eaphan/GLENet#13]

**Comment by 15041909992** [comment]
AttributeError: module 'spconv' has no attribute 'SparseModule'

**Comment by Eaphan** [comment]
Maybe it's caused by spconv version. If you use spconv 2.0, you can use "from spconv.pytorch.modules import SparseModule, SparseSequential".

You can try:

try:
    import spconv.pytorch as spconv
except:
    import spconv as spconv
