### ISSUE TITLE
How to use other datasets for training?

### ISSUE THREAD

**Issue by mihui20** [Eaphan/GLENet#15]
I encountered a problem while using other autonomous driving datasets
->Self. prior, mux, logvarx=self. x_ Encoder (x)
(Pdb)
During breakpoint debugging, I found that batch_ There is a null value in dict ['gt'boxes_input '], may I ask why this is
Looking forward to your reply，thank you

**Comment by Eaphan** [comment]
Please convert you used dataset into the format of KITTI. 
See the code in [cvae_uncertainty/dataset.py](https://github.com/Eaphan/GLENet/blob/a07af6c11467b8df44750ff019f22962f3d0d711/cvae_uncertainty/dataset.py#L431)
        box3d_lidar_ori = info['box3d_lidar']
        
 You should fill valid annotation of 3d boxes in the *info.pkl files.
