### ISSUE TITLE
How could I get '../data/kitti/kitti_dbinfos_val.pkl'?

### ISSUE THREAD

**Issue by 2020427933** [Eaphan/GLENet#17]
When I run GLENet Prediction, There is the error : No such file or directory: '../data/kitti/kitti_dbinfos_val.pkl'
How could I solve this problem?

**Comment by Eaphan** [comment]
Do you follow the instructions in the "[Generate Label Uncertainty with GLEnet](https://github.com/Eaphan/GLENet#generate-label-uncertainty-with-glenet)" part of README.md?

Please rename the provided files:
kitti_infos_train_wconf_v5.pkl -> kitti_infos_train.pkl
kitti_dbinfos_train_wconf_v5.pkl -> kitti_dbinfos_train.pkl

**Comment by 2020427933** [comment]
> Do you follow the instructions in the "[Generate Label Uncertainty with GLEnet](https://github.com/Eaphan/GLENet#generate-label-uncertainty-with-glenet)" part of README.md?
> 
> Please rename the provided files: kitti_infos_train_wconf_v5.pkl -> kitti_infos_train.pkl kitti_dbinfos_train_wconf_v5.pkl -> kitti_dbinfos_train.pkl

Yes,I have followed the instructions,and I got :
kitti_infos_test.pkl
kitti_dbinfos_train.pkl
kitti_infos_train.pkl
kitti_infos_val.pkl
kitti_infos_trainval.pkl

But there isn't "kitti_dbinfos_val.pkl".
Is it necessary?
How could I generate this file?

**Comment by Eaphan** [comment]
Yes. If you want to test the performance of GLENet, you should generate the file.
But if you just want to generate label uncertainty for downstream detectors, you should follow the instructions in README.md and do not need that file.
