### ISSUE TITLE
Is there a training model for Car, Pedistrian and Cyclist? I think you only released the training model of Car.

### ISSUE THREAD

**Issue by 6Superman6** [Eaphan/GLENet#2]
Is there a training model for Car, Pedistrian and Cyclist? I think you only released the training model of Car.

**Comment by 6Superman6** [comment]
Maybe I can try to modify it myself

**Comment by Eaphan** [comment]
Yeah, the process for the pedestrian and cyclist is similar to that of car. You can try to modify it yourself.
