### ISSUE TITLE
 I want to generate the indeterminate label of pedestrians and bicycles. How to do?

### ISSUE THREAD

**Issue by 6Superman6** [Eaphan/GLENet#4]
I also want to generate the indeterminate label of pedestrians and bicycles
Can you tell me which files need to be modified? Or you can tell me how to modify the following four files:

（1）GLENet/cvae_ uncertainty/cfgs/exp20_ gen_ ori.yaml

（2）GLENet/cvae_ uncertainty/dataset.py

（3）GLENet/cvae_ uncertainty/mapping_ uncertainty.py

（4）GLENet/cvae_ uncertainty/change_ gt_ infos.py

I have also modified these four files myself, and I have contacted you via email. I hope the teacher can see if I have modified them correctly.

**Comment by Eaphan** [comment]
Let's discuss it in the issues so other people who have the same issues can have the answer.

**Comment by Eaphan** [comment]
You can try to submit a pull request so I can help you review the code online.

**Comment by 20181102931** [comment]
您好，请问可以具体说明如何生成行人和自行车的不确定标签吗？

**Comment by Eaphan** [comment]
In the cvae_uncertainty directory, we provide code for generating label uncertainty for the car category. You can modify the code to accommodate pedestrians and cyclists.

**Comment by 20181102931** [comment]
感谢您的回复！还有一个问题是请问是通过直接修改，然后运行exp20_gen.yaml来可以生成不确定标签吗？



At 2024-10-30 16:14:59, "Yifan Zhang" ***@***.***> wrote:

In the cvae_uncertainty directory, we provide code for generating label uncertainty for the car category. You can modify the code to accommodate pedestrians and cyclists.
